<?php 
    $imagenes=array(
        "Planeta1"=>"imagen1.jpeg",
        "Concienciacion"=>"imagen2.jpeg",
        "Contaminacion"=>"imagen3.jpeg",
        "Planeta2"=>"imagen4.jpg",
        "NoContaminacion"=>"imagen5.jpg",
        "SalvarPlaneta"=>"imagen6.jpeg",
    );
?>